[phases.build]
cmds = [
  "npm install --legacy-peer-deps",
  "npm run build --workspace=apps/shared",
  "npm run build --workspace=apps/backend"
]

[start]
cmd = "npm run prisma:deploy --workspace=apps/backend && node apps/backend/dist/src/main.js"
