[phases.build]
cmds = [
  "rm -rf node_modules/.cache",
  "npm ci --include-workspace-root",
  "npm run build --workspace=apps/shared",
  "npm run build --workspace=apps/backend"
]

[phases.start]
cmd = "node apps/backend/dist/src/main.js"

[start]
cmd = "node apps/backend/dist/src/main.js"
